CREATE EXTENSION IF NOT EXISTS postgis;

DROP TABLE IF EXISTS DOCTOR_AVAILABILITY CASCADE;
DROP TABLE IF EXISTS DOCTOR CASCADE;

CREATE TABLE DOCTOR (
    DoctorID SERIAL PRIMARY KEY,
    FullName VARCHAR(100) NOT NULL,
    PhoneNumber VARCHAR(15) NOT NULL,
    Specialization VARCHAR(50) NOT NULL
);

CREATE TABLE DOCTOR_AVAILABILITY (
    AvailabilityID SERIAL PRIMARY KEY,
    DoctorID INT UNIQUE REFERENCES DOCTOR(DoctorID) ON DELETE CASCADE,
    Status VARCHAR(20) DEFAULT 'Available' CHECK (Status IN ('Available', 'Busy', 'Off-Duty')),
    CurrentLocation GEOMETRY(Point, 4326),
    LastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
